name: "Setup"
description: "Setup Composite Action"

runs:
  using: "composite"

  steps:
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: "stable"
        cache: true

    - name: Version
      run: |
        flutter --version
        dart --version
      shell: bash

    - name: "Cache pubspec dependencies"
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.PUB_CACHE }}
          **/.packages
          **/.flutter-plugins
          **/.flutter-plugin-dependencies
          **/.dart_tool/package_config.json
        key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}
        restore-keys: |
          build-pubspec-
