name: "Build for Linux"
description: "Build for Linux Composite Action"

runs:
  using: "composite"

  steps:
    - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
      shell: bash

    - run: flutter config --enable-linux-desktop
      shell: bash

    - run: flutter build linux ${{ env.FLUTTER_BUILD_ARGS }} ${{ inputs.obfuscation && '--obfuscate --split-debug-info=build/linux' || '' }}
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: build-linux
        path: build/linux
