name: "Check"
description: "Check Composite Action"

runs:
  using: "composite"

  steps:
    - name: Analyze
      run: flutter analyze
      shell: bash

    - name: Test
      run: |
        dart pub global activate junitreport
        flutter test --machine | tojunit --output test-report.xml
      shell: bash

    - uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: test-report.xml
        annotate_only: true
        detailed_summary: true
