name: "Build for Android"
description: "Build for Android Composite Action"

inputs:
  obfuscation:
    description: "Obfuscation"
    default: "true"

runs:
  using: "composite"

  steps:
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: "11"
        distribution: "temurin"
        cache: gradle

    - run: |
        flutter build apk ${{ env.FLUTTER_BUILD_ARGS }} ${{ fromJSON(inputs.obfuscation) && '--obfuscate --split-debug-info=build/app/outputs/flutter-apk' || '' }}
      shell: bash

    - run: flutter build apk ${{ env.FLUTTER_BUILD_ARGS }} ${{ fromJSON(inputs.obfuscation) && '--obfuscate --split-debug-info=build/app/outputs/flutter-apk' || '' }}
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: build-apk
        path: build/app/outputs/flutter-apk

    - run: flutter build appbundle ${{ env.FLUTTER_BUILD_ARGS }} ${{ fromJSON(inputs.obfuscation) && '--obfuscate --split-debug-info=build/app/outputs/bundle/release' || '' }}
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: build-appbundle
        path: build/app/outputs/bundle/release
