name: Flutter CI

on:
  workflow_dispatch:
    inputs:
      run_check:
        description: "Run: Check"
        type: boolean
        default: true
      run_build_android:
        description: "Run: Build for Android"
        type: boolean
        default: true
      run_build_ios:
        description: "Run: Build for iOS"
        type: boolean
        default: true
      run_build_web:
        description: "Run: Build for Web"
        type: boolean
        default: true
      run_build_windows:
        description: "Run: Build for Windows"
        type: boolean
        default: true
      run_build_linux:
        description: "Run: Build for Linux"
        type: boolean
        default: true
      run_build_macos:
        description: "Run: Build for macOS"
        type: boolean
        default: true
      build_number:
        description: "Build Number (ex. 123)"
        type: string
      build_name:
        description: "Build Name (ex. 1.2.3)"
        type: string
      obfuscation:
        description: "Obfuscation"
        type: boolean
        default: true

permissions:
  contents: read
  actions: read
  checks: write

env:
  # https://docs.flutter.dev/release/archive
  FLUTTER_VERSION: "3.13.9"
  FLUTTER_BUILD_ARGS: >-
    ${{ inputs.build_number != '' && format('--build-number {0}', inputs.build_number) || '' }}
    ${{ inputs.build_name != '' && format('--build-name {0}', inputs.build_name) || '' }}

jobs:
  check:
    name: "Check"
    if: inputs.run_check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check
        uses: ./.github/actions/check

  build_android:
    name: "Build for Android"
    needs: [ check ]
    if: (!cancelled() && !failure()) && inputs.run_build_android

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build for Android
        uses: ./.github/actions/build_android
        with:
          obfuscation: ${{ toJSON(inputs.obfuscation) }}

  build_ios:
    name: "Build for iOS"
    needs: [ check ]
    if: (!cancelled() && !failure()) && inputs.run_build_ios

    runs-on: macos-13
    env:
      # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode
      DEVELOPER_DIR: "/Applications/Xcode_15.0.1.app/Contents/Developer"

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build for iOS
        uses: ./.github/actions/build_ios
        with:
          obfuscation: ${{ toJSON(inputs.obfuscation) }}

  build_web:
    name: "Build for Web"
    needs: [ check ]
    if: (!cancelled() && !failure()) && inputs.run_build_web

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build for Web
        uses: ./.github/actions/build_web

  build_windows:
    name: "Build for Windows"
    needs: [ check ]
    if: (!cancelled() && !failure()) && inputs.run_build_windows

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build for Windows
        uses: ./.github/actions/build_windows

  build_linux:
    name: "Build for Linux"
    needs: [ check ]
    if: (!cancelled() && !failure()) && inputs.run_build_linux

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build for Linux
        uses: ./.github/actions/build_linux

  build_macos:
    name: "Build for macOS"
    needs: [ check ]
    if: (!cancelled() && !failure()) && inputs.run_build_macos

    runs-on: macos-13
    env:
      # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode
      DEVELOPER_DIR: "/Applications/Xcode_15.0.1.app/Contents/Developer"

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build for macOS
        uses: ./.github/actions/build_macos
