name: Flutter CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "README.md"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  actions: read

env:
  FLUTTER_BUILD_ARGS:

jobs:
  check:
    name: "Check"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check
        uses: ./.github/actions/check
