name: Flutter CD

on:
  workflow_dispatch:
    inputs:
      run_check:
        description: "Run: Check"
        type: boolean
        default: true
      run_build_android:
        description: "Run: Build for Android"
        type: boolean
        default: true
      run_build_ios:
        description: "Run: Build for iOS"
        type: boolean
        default: true
      run_build_web:
        description: "Run: Build for Web"
        type: boolean
        default: true
      run_build_windows:
        description: "Run: Build for Windows"
        type: boolean
        default: true
      run_build_linux:
        description: "Run: Build for Linux"
        type: boolean
        default: true
      run_build_macos:
        description: "Run: Build for macOS"
        type: boolean
        default: true
      build_number:
        description: "Build Number (ex. 123)"
        type: string
      build_name:
        description: "Build Name (ex. 1.2.3)"
        type: string
      obfuscation:
        description: "Obfuscation"
        type: boolean
        default: true

permissions:
  contents: read
  actions: read

env:
  FLUTTER_BUILD_ARGS: >-
    ${{ inputs.build_number != '' && format('--build-number {0}', inputs.build_number) || '' }}
    ${{ inputs.build_name != '' && format('--build-name {0}', inputs.build_name) || '' }}

jobs:
  check:
    name: "Check"
    if: inputs.run_check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Check
        uses: ./.github/actions/check

  build_android:
    name: "Build for Android"
    needs: check
    if: (!cancelled() && !failure()) && inputs.run_build_android

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build for Android
        uses: ./.github/actions/build_android
        with:
          obfuscation: ${{ toJSON(inputs.obfuscation) }}

  build_ios:
    name: "Build for iOS"
    needs: check
    if: (!cancelled() && !failure()) && inputs.run_build_ios

    runs-on: macos-13
    env:
      # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode
      DEVELOPER_DIR: "/Applications/Xcode_15.0.1.app/Contents/Developer"

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build for iOS
        uses: ./.github/actions/build_ios
        with:
          obfuscation: ${{ toJSON(inputs.obfuscation) }}

  build_web:
    name: "Build for Web"
    needs: check
    if: (!cancelled() && !failure()) && inputs.run_build_web

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build for Web
        uses: ./.github/actions/build_web

  build_windows:
    name: "Build for Windows"
    needs: check
    if: (!cancelled() && !failure()) && inputs.run_build_windows

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build for Windows
        uses: ./.github/actions/build_windows

  build_linux:
    name: "Build for Linux"
    needs: check
    if: (!cancelled() && !failure()) && inputs.run_build_linux

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build for Linux
        uses: ./.github/actions/build_linux

  build_macos:
    name: "Build for macOS"
    needs: check
    if: (!cancelled() && !failure()) && inputs.run_build_macos

    runs-on: macos-13
    env:
      # https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode
      DEVELOPER_DIR: "/Applications/Xcode_15.0.1.app/Contents/Developer"

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build for macOS
        uses: ./.github/actions/build_macos

  release:
    name: "Release"
    needs:
      - build_android
      - build_ios
      - build_web
      - build_windows
      - build_linux
      - build_macos
    if: (!cancelled() && !failure())

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          VERSION_NAME=$(yq '.version | sub("[+].*","")' pubspec.yaml)
          VERSION_NUMBER=$(yq '.version | sub(".*[+]","")' pubspec.yaml)
          echo "VERSION_NAME=${{ inputs.build_name != '' && format('"{0}"', inputs.build_name) || '$VERSION_NAME' }}" >> $GITHUB_OUTPUT
          echo "VERSION_NUMBER=${{ inputs.build_number != '' && format('"{0}"', inputs.build_number) || '$VERSION_NUMBER' }}" >> $GITHUB_OUTPUT
        shell: bash
        id: version

      - uses: actions/download-artifact@v4
        with:
          name: build-apk
          path: build/app/outputs/flutter-apk
        if: needs.build_android.result == 'success'
      - uses: actions/download-artifact@v4
        with:
          name: build-appbundle
          path: build/app/outputs/bundle/release
        if: needs.build_android.result == 'success'
      - run: |
          cd build/app
          zip -r ../android.zip ./outputs/flutter-apk ./outputs/bundle/release
        shell: bash
        if: needs.build_ios.result == 'success'

      - uses: actions/download-artifact@v4
        with:
          name: build-ios
          path: build/ios/iphoneos
        if: needs.build_ios.result == 'success'
      - uses: actions/download-artifact@v4
        with:
          name: build-ipa
          path: build/ios/archive
        if: needs.build_ios.result == 'success'
      - run: |
          cd build/ios
          zip -r ../ios.zip ./iphoneos ./archive
        shell: bash
        if: needs.build_ios.result == 'success'

      - uses: actions/download-artifact@v4
        with:
          name: build-web
          path: build/web
        if: needs.build_web.result == 'success'
      - run: |
          cd build/web
          zip -r ../web.zip .
        shell: bash
        if: needs.build_web.result == 'success'

      - uses: actions/download-artifact@v4
        with:
          name: build-windows
          path: build/windows
        if: needs.build_windows.result == 'success'
      - run: |
          cd build/windows
          zip -r ../windows.zip .
        shell: bash
        if: needs.build_windows.result == 'success'

      - uses: actions/download-artifact@v4
        with:
          name: build-linux
          path: build/linux
        if: needs.build_linux.result == 'success'
      - run: |
          cd build/linux
          zip -r ../linux.zip .
        shell: bash
        if: needs.build_linux.result == 'success'

      - uses: actions/download-artifact@v4
        with:
          name: build-macos
          path: build/macos
        if: needs.build_macos.result == 'success'
      - run: |
          cd build/macos
          zip -r ../macos.zip .
        shell: bash
        if: needs.build_macos.result == 'success'

      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.VERSION_NAME }}+${{ steps.version.outputs.VERSION_NUMBER }}
          target_commitish: ${{ github.sha }}
          draft: true
          files: |
            build/android.zip
            build/ios.zip
            build/web.zip
            build/windows.zip
            build/linux.zip
            build/macos.zip

  notify:
    name: "Notify"
    needs:
      - check
      - build_android
      - build_ios
      - build_web
      - build_windows
      - build_linux
      - build_macos
      - release
    if: always()

    runs-on: ubuntu-latest

    steps:
      - name: Assign
        id: assign
        run: |
          echo "slack_webhook_url=${{ secrets.SLACK_WEBHOOK_URL }}" >> $GITHUB_OUTPUT

      - name: Slack Payload
        id: slack_payload
        uses: actions/github-script@v7
        with:
          script: |
            const env = process.env;
            const needs = JSON.parse(env.NEEDS);
            const counts = Object.entries(needs).reduce((acc, curr) => {
              const [key, value] = curr;
              const result = value.result;
              acc[result] = acc[result] ? acc[result] + 1 : 1;
              return acc;
            }, {});
            const results = Object.entries(counts).map(([key, value]) => `${key}: ${value}`);
            const repository = `${context.repo.owner}/${context.repo.repo}`;
            const url = `${context.serverUrl}/${repository}/actions/runs/${context.runId}`;
            const texts = [
              `[${repository}] Run: ${context.workflow} - ${context.ref} (${context.sha})`,
              `${url}`,
              ...results
            ];
            const text = texts.join("\n");
            const color = counts["failure"] ? "danger" :  "good";
            const fields = [{
              "title": counts["failure"] ? "Failure" :  "Success"
            }];
            return {
              text, color, fields
            };
        env:
          NEEDS: ${{ toJSON(needs) }}

      - uses: slackapi/slack-github-action@v1.25.0
        if: steps.assign.outputs.slack_webhook_url != ''
        with:
          payload: ${{ steps.slack_payload.outputs.result }}
        env:
          SLACK_WEBHOOK_URL: ${{ steps.assign.outputs.slack_webhook_url }}

  actions_timeline:
    name: "Actions Timeline"
    needs: notify
    if: always()

    runs-on: ubuntu-latest

    steps:
      - uses: Kesin11/actions-timeline@v2
