name: Flutter CI

on:
  # push:
    # branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]
  workflow_dispatch:
    inputs:
      run_build_android:
        description: "Run: Build for Android"
        type: boolean
        default: true
      run_build_ios:
        description: "Run: Build for iOS"
        type: boolean
        default: true
      run_build_web:
        description: "Run: Build for Web"
        type: boolean
        default: true
      run_build_windows:
        description: "Run: Build for Windows"
        type: boolean
        default: true

permissions:
  contents: read
  actions: read
  checks: write

env:
  FLUTTER_VERSION: '3.13.9'

jobs:
  check:
    name: "Check"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup
      uses: ./.github/actions/setup

    - name: Analyze
      run: flutter analyze

    - name: Test
      run: flutter test --machine > test-report.json

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
          name: Flutter Tests
          path: test-report.json
          reporter: flutter-json
          fail-on-error: true

  build_android:
    name: "Build for Android"
    needs: [check]
    if: inputs.run_build_android

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Setup
      uses: ./.github/actions/setup

    - run: flutter build apk
    - uses: actions/upload-artifact@v3
      with:
        name: build-apk
        path: build/app/outputs/flutter-apk

    - run: flutter build appbundle
    - uses: actions/upload-artifact@v3
      with:
        name: build-appbundle
        path: build/app/outputs/bundle/release

  build_ios:
    name: "Build for iOS"
    needs: [check]
    if: inputs.run_build_ios

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup
      uses: ./.github/actions/setup

    - run: flutter build ios --simulator
    - uses: actions/upload-artifact@v3
      with:
        name: build-ios_simulator
        path: build/ios/iphonesimulator

    - run: flutter build ios --no-codesign
    - uses: actions/upload-artifact@v3
      with:
        name: build-ios
        path: build/ios/iphoneos

    - run: flutter build ipa --no-codesign
    - uses: actions/upload-artifact@v3
      with:
        name: build-ipa
        path: build/ios/archive

  build_web:
    name: "Build for Web"
    needs: [check]
    if: inputs.run_build_web

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - run: flutter build web
      - uses: actions/upload-artifact@v3
        with:
          name: build-web
          path: build/web

  build_windows:
    name: "Build for Windows"
    needs: [check]
    if: inputs.run_build_windows

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - run: flutter config --enable-windows-desktop

      - run: flutter build windows
