name: Flutter CI

on:
  # push:
    # branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]
  workflow_dispatch:
    inputs: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.9'
        channel: 'stable'

    - name: Version
      run: flutter --version

    - name: Analyze
      run: flutter analyze

    - name: Test
      run: flutter test
